name: metal-defect-eval

channels:
  - conda-forge

dependencies:
  - python=3.14
  - jupyterlab
  - jupyter
  - ipykernel
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - plotly
  - scikit-learn
  - xgboost
  - imbalanced-learn
  - joblib
  - quarto
  - pip
  - pip:
      - ucimlrepo